### ISSUE TITLE
Add Error Handling Support for Custom Message or Attribute [IDEA]

### ISSUE THREAD

**Issue by theonly27** [luigel/laravel-paymongo#11]
### Versions

* PHP version: 7.3
* Laravel version: 8.11
* Package version: 1.2

### Description

I want to customize the error callback attribute or message.

### Example

  * details.card_number format is invalid
this is generated in the package by using try catch.
is this possible to make this work like the default laravel validation? that it would return a validation exception.

### Additional Information

Any additional information, configuration or data that might be needed to understand the proposal.

**Comment by luigel** [comment]
@theonly27 Actually this is not good for the package. Since it will be less customizable. What I can do for this is to send the whole error message sent from Paymongo so that we can just make our own validation from the Paymongo's error message. 

This is a sample error message from Paymongo.

```
{"errors":[{"code":"resource_failed_state","detail":"The card has insufficient funds to complete the purchase.","sub_code":"insufficient_funds"}]}
```

**Comment by theonly27** [comment]
Thanks master!
