### ISSUE TITLE
[BUG]   syntax error, unexpected ')' in Traits/HasCommandValidation.php:14

### ISSUE THREAD

**Issue by carlmagumpara** [luigel/laravel-paymongo#22]
### Prerequisites

* [X] Are you using Laravel 6 and above?
* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Paymongo.
* [X] Checked that your issue isn't already filed.
* [X] Checked if no PR was submitted that fixes this problem.
* [X] Filled in the entire issue template

### Versions

* PHP version: 7.2 
* Laravel version: 7 
* Package version: Latest 

### Description

        $validator = Validator::make(
            $data,
            $rules, <--- remove comma here
        );

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:** 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by luigel** [comment]
@carlmagumpara will tag this fix tomorrow. Thank you for reporting 😀🙏
