### ISSUE TITLE
Paymongo Error when passing a tenth or hundredth decimal in amount argument

### ISSUE THREAD

**Issue by abenojardev** [luigel/laravel-paymongo#28]
### Prerequisites 

* [x] Are you using Laravel 6 and above?
* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Paymongo.
* [x] Checked that your issue isn't already filed.
* [x] Checked if no PR was submitted that fixes this problem.
* [x] Filled in the entire issue template

### Versions 

* PHP version: 
	PHP 7.3.8 (cli) (built: Aug 11 2019 20:50:16) ( NTS )
	Copyright (c) 1997-2018 The PHP Group
	Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
	    with Zend OPcache v7.3.8, Copyright (c) 1999-2018, by Zend Technologies
	    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

* Laravel version: 
	Laravel Framework 7.28.3

* Package version: 
	luigel/laravel-paymongo : ^1.3.1

### Description

	Paymongo only accepts integer in the argument amount,

	looking at the package, we have a method there convertPayloadAmountsToInteger($payload)
	that converts the passed amount from app to package class. 
       
	In the app we are developing, our products price are in hundredth decimal (P 112.529) 
	Passing this in Paymongo::paymentIntent->create([]), returns a paymongo exception
	"amount should be an integer"  

### Steps to Reproduce

	1. Please create a file tests/AmounToIntegerTest.php
	2. Copy this code into tests/AmounToIntegerTest.php

        <?php

			namespace Luigel\Paymongo\Tests;

			use Luigel\Paymongo\Models\BaseModel;
			use Luigel\Paymongo\Traits\Request;

			class AmounToIntegerTest extends BaseTestCase
			{
			    use Request; 

			    /** @test */
			    public function it_can_convert_without_decimal()
			    { 
			    	$payload = [
			    		'amount' => 147
			    	];

			    	$convertedPayload = $this->convertPayloadAmountsToInteger($payload);

			        $this->assertIsInt($convertedPayload['amount']);  
			        $this->assertIsNotFloat($convertedPayload['amount']);
			    }

			    /** @test */
			    public function it_can_convert_with_in_tenth_decimal()
			    { 
			    	$payload = [
			    		'amount' => 147.95
			    	];

			    	$convertedPayload = $this->convertPayloadAmountsToInteger($payload);

			        $this->assertIsInt($convertedPayload['amount']); 
			        $this->assertIsNotFloat($convertedPayload['amount']);
			    }

			    /** @test */
			    public function it_can_convert_with_in_hundredth_decimal()
			    { 
			    	$payload = [
			    		'amount' => 254.950
			    	];

			    	$convertedPayload = $this->convertPayloadAmountsToInteger($payload);

			        $this->assertIsInt($convertedPayload['amount']); 
			        $this->assertIsNotFloat($convertedPayload['amount']);
			    }
			}  

	3. composer test 

	There were 2 failures:

	1) Luigel\Paymongo\Tests\AmounToIntegerTest::it_can_convert_with_in_tenth_decimal
	Failed asserting that 14794.999999999998 is of type "int".

	/Users/macbook/Documents/Docker/nutriasia/laravel-paymongo/tests/AmounToIntegerTest.php:34

	2) Luigel\Paymongo\Tests\AmounToIntegerTest::it_can_convert_with_in_hundredth_decimal
	Failed asserting that 25495.0 is of type "int".

	/Users/macbook/Documents/Docker/nutriasia/laravel-paymongo/tests/AmounToIntegerTest.php:47

	FAILURES!
	Tests: 3, Assertions: 4, Failures: 2.

**Expected behavior:** 

	Assuming we have 
		147.95 
		should return 14795

		254.950
		should return 25495

**Actual behavior:**   

	Assuming we have 
		147 
		convertPayloadAmountsToInteger() will return it as 14700
		this is integer (correct)

		147.95 
		convertPayloadAmountsToInteger() will return it as 14794.999999999998
		this is not an integer (error)

		254.950
		convertPayloadAmountsToInteger() will return it as 25495.0
		this is not an integer (error)

### Additional Information
        none

**Comment by abenojardev** [comment]
Hi sir @luigel 

I added a pr at #29
Would be great if we could patch this one, or suggest a fix.  

Thank you

**Comment by luigel** [comment]
Thank you! @abenojardev will tag a new version.
