### ISSUE TITLE
[BUG] Call to undefined method Luigel\Paymongo\Paymongo::payment()

### ISSUE THREAD

**Issue by sironronron** [luigel/laravel-paymongo#3]
After creating a source and receiving a webhook data I'm using Paymongo::payment() to create a payment for the source.chargeable.

I get this error "Call to undefined method Luigel\Paymongo\Paymongo::payment()". But the method exists.

**Comment by luigel** [comment]
Can you post a snippet of your code?

**Comment by sironronron** [comment]
Im already importing

`use Luigel\Paymongo\Facades\Paymongo`

and tried

`use Luigel\Paymongo\Paymongo;`

Here's the code

`public function handle()
    {

        $payment = Paymongo::payment()->create([
            'amount' => 55900,
            'currency' => 'PHP',
            'description' => 'Testing payment',
            'statement_descriptor' => 'Test Paymongo',
            'source' => [
                'id' => 'src_AvX628NWYoG1WmrJespGgLTt',
                'type' => 'source.chargeable'
            ]
        ]);

        logger($payment);

        return response()
            ->json([
                'successfulPayment' => $payment
            ], 200);
    }`

**Comment by luigel** [comment]
@sironronron I'm using laravel-paymongo v1.1.1. What version are you using?

**Comment by sironronron** [comment]
I'm also using laravel-paymongo v1.1.1. Should I re-install it? 

Thanks. Changed it.

**Comment by sironronron** [comment]
Re-installed it and now using laravel-paymongo v1.1.2.

Thanks.
