### ISSUE TITLE
Paymaya supported?

### ISSUE THREAD

**Issue by marcusaaronb** [luigel/laravel-paymongo#40]
Hello dev team
Paymaya is supported?

**Comment by abenojardev** [comment]
return_url is required by default

return_url = Where will paymong post payment status or redirect customer upon success, failed payment.

**Comment by abenojardev** [comment]
Paymongo Paymaya by the way will create a checkout url where the users will process the payment,

with this return_url is very crucial on the process because we are redirecting users to different domains

**Comment by marcusaaronb** [comment]
How can i integrate with attach?

**Comment by luigel** [comment]
@marcusaaronb Oh ok. I think hindi pa supported yung paymaya sa package. I also reproduced that while rewriting the test cases. Ill try to add a support in paymaya. But PR is very welcome for this one :D
