### ISSUE TITLE
[Documentation Issue] Amount Conversion to integer

### ISSUE THREAD

**Issue by stonedleaf** [luigel/laravel-paymongo#48]
Please add documentation on the amount value conversion used by the package.
The function `convertPayloadAmountsToInteger` conflicts a little bit with PayMongo's documentation.

PayMongo's documentation says that the amount value should be an integer. 
However, this package's code does the conversion to integer automatically.

Here are my suggestions for this issue. Kindly check which works best
1) maybe add new config in `config/paymongo.php` so that devs can decide to use the package's own conversion or not. 
2) use `'amount' => 100.50',` in the example code in the documentation (reference: https://paymongo.rigelkentcarbonel.com/payment-intents#sample-2). However, I think the package might still conflict with other PHP packages like moneyphp/money (which I'm currently using)
3) follow PayMongo's convention, 

Thank you!

**Comment by luigel** [comment]
Hi. Yes you are correct. PR is very welcome here. So if you can create a PR for this that would be great.

**Comment by luigel** [comment]
@stonedleaf Hi. I created PR for this one. Can you check if it will fix your problem? Or suggest something that might be a good addition to the package? https://github.com/luigel/laravel-paymongo/pull/50

**Comment by stonedleaf** [comment]
hi @luigel it is ok with me. Thank you!

**Comment by luigel** [comment]
@stonedleaf I tagged it in version v2.1.0 (php8) or v1.5.0 (php7.4)
