### ISSUE TITLE
[IDEA] Paymaya Feature

### ISSUE THREAD

**Issue by johanpaolorodriguez** [luigel/laravel-paymongo#56]
### Description

Requesting Paymaya API Integration to be added to this package https://developers.paymongo.com/docs/accepting-paymaya-payments

**Comment by luigel** [comment]
@johanpaolorodriguez Check this issue. https://github.com/luigel/laravel-paymongo/issues/40 

I already implemented the support for Paymaya in this PR #44

**Comment by johanpaolorodriguez** [comment]
Oh right, awesome, thanks!
