### ISSUE TITLE
Gcash Payment help

### ISSUE THREAD

**Issue by eskiesirius** [luigel/laravel-paymongo#68]
Do I need to create a webhook or i can just directly use this?

```
$gcashSource = Paymongo::source()->create([
    		'type' => 'gcash',
    		'amount' => 100.00,
    		'currency' => 'PHP',
    		'redirect' => [
    			'success' => 'http://localhost:8000/success',
    			'failed' => 'http://localhost:8000/failed'
    		]
    	]);
```

actually i didn't understand when to use webhook

**Comment by luigel** [comment]
@eskiesirius Better to read their documentation regarding gcash. https://developers.paymongo.com/docs/accepting-gcash-payments

**Comment by eskiesirius** [comment]
thats why im having a problem understanding it because using the code above will produce checkout url where the customer can pay so im wondering when will the webhook occured..

**Comment by eskiesirius** [comment]
does webhook will trigger after successful payment?
