### ISSUE TITLE
[BUG]PHP 8 Support

### ISSUE THREAD

**Issue by eskiesirius** [luigel/laravel-paymongo#71]
### Prerequisites

* [x] Are you using Laravel 6 and above?
* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Paymongo.
* [ ] Checked that your issue isn't already filed.
* [ ] Checked if no PR was submitted that fixes this problem.
* [ ] Filled in the entire issue template

### Versions

* PHP version: 8.1
* Laravel version: 8
* Package version: v1.5.0

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:** 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by luigel** [comment]
Please add more information.

**Comment by eskiesirius** [comment]
Sorry.. i was using v1.5 for php 8.1..
