### ISSUE TITLE
[BUG] Implement 3D Secure using this library?

### ISSUE THREAD

**Issue by carlmagumpara** [luigel/laravel-paymongo#9]
### Prerequisites

* [x] Are you using Laravel 6 and above?
* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Paymongo.
* [x] Checked that your issue isn't already filed.
* [ ] Checked if no PR was submitted that fixes this problem.
* [ ] Filled in the entire issue template

### Versions

* PHP version: 
* Laravel version: 
* Package version: 

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:** 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by luigel** [comment]
You can read the documentation in Paymongo's website. https://developers.paymongo.com/docs/accepting-cards you'll need to check if the `paymentIntent` was `succeeded` or `awaiting_next_action` if it is `awaiting_next_action` you will need to show the modal for the OTP.
